import React from "react"
import BackToTopElem from "./BackToTopElem"
const BackToTop = () => {
	return (
		<div>
			<div className="border-t-[1px] border-[#DCDAD9] dark:border-[#222222] hover:dark:border-[#DCDAD9] text-[#DCDAD9] hover:text-[#213B86] hover:dark:text-[#dcdad9] dark:text-[#222222] dark:hidden backToTopHover">
				<a
					href="#"
					className="flex justify-start items-center font-SofiaSans text-[5vw] md:text-[2.5vw] uppercase ml-[0%] leading-none whitespace-nowrap tracking-[-0.03em]"
				>
					<div className="messageDefilantHover ml-[-40px] p-4">
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
					</div>
				</a>
			</div>
			<div className="border-t-[1px] border-[#DCDAD9] dark:border-[#222222] hover:dark:border-[#DCDAD9] text-[#DCDAD9] hover:text-[#213B86] hover:dark:text-[#dcdad9] dark:text-[#222222] hidden dark:block backToTopHoverDark">
				<a
					href="#"
					className="flex justify-start items-center font-SofiaSans text-[5vw] md:text-[2.5vw] uppercase ml-[0%] leading-none whitespace-nowrap tracking-[-0.03em]"
				>
					<div className="messageDefilantHover ml-[-40px] p-4">
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
						<BackToTopElem></BackToTopElem>
					</div>
				</a>
			</div>
		</div>
	)
}

export default BackToTop
